'''
Write a program to generate Fibonacci series of numbers.
    Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
  Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
   b) Generate the series until the element in the series is less than Max number.
'''

a=0
b=1
n=int(raw_input("Enter the number of terms needed "))

list1 = [a,b]

while(n-2):
    c=a+b
    a=b
    b=c
    list1.append(c)
    n=n-1


for integer in list1:
    print integer

m=int(raw_input("Enter the number until which the series is to be printed "))
a=0
b=1

list1 = [a,b]

while(m-2):
    c=a+b
    if(c>m):
        break
    a=b
    b=c
    list1.append(c)
    m=m-1

for integer in list1:
    print integer
